'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PAX
    Public Property Id As Integer
    Public Property Type As String
    Public Property Year As Long
    Public Property Location As String
    Public Property SwagId As Integer

    Public Overridable Property Swag As Swag

End Class
